### ISSUE TITLE
Rat!!!

### ISSUE THREAD

**Issue by InclusiveMe** [TheVideoEffect/GrowtopiaAutofarmMenu#2]
Lmfao who ever will fall for this crap that is main.py gotta be total idiot, there isnt even any icon its not even .exe dumb creator

**Comment by ryannn2424** [comment]
Re-read and Re-watch the comments on this video: https://www.youtube.com/watch?v=5fyya6wHILQ

If that's too hard for some reason, run "`pip3 install pynput pysimplegui pause`", then right click and run the main.py file.

This is not an .exe file because this is not a windows executable, but a python script.
